Replace install-gpu-drivers script with chwd autoconfiguration
CachyOS/cachyos-calamares pull request #32
Opened 2024-08-22 17:05 UTC by ventureoo

This makes debugging a bit easier for us, as it allows to reproduce errors related to drivers setup after installation.

2024-08-22 17:15 UTC, vnepogodin commented
idk about cases where we might want to install multiple profiles. in that case if intel igpu is upper in the list to be picked, then it will install only for intel igpu and nothing will be installed for nvidia dgpu (same for amd)

2024-09-07 18:22 UTC, vnepogodin requested changes

2024-09-07 18:22 UTC, vnepogodin commented on src/modules/chwd/main.py
> +    shell_command = ["arch-chroot", root_mount_point, "chwd --autoconfigure"]
```suggestion
    shell_command = ["arch-chroot", root_mount_point, "chwd", "--autoconfigure"]
```

arch-chroot pass arguments as-is

2024-09-09 21:04 UTC, vnepogodin approved these changes
LGTM

was confirmed that its working

2024-11-08 17:00 UTC, ventureoo commented
Has been manually merged (https://github.com/CachyOS/cachyos-calamares/commit/26c120952c9c97867d9c51862875dcd6248f3c96), so closing.

2024-11-08 17:00 UTC, closed without merging